version: "3.8"
services:
  server:
    build: .
    env_file:
      - .env
    ports:
      - 8090:8090
    volumes:
      - .:/usr/src/app
      - ./server:/usr/src/app/server:include
    command: go run main.go -b 0.0.0.0
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
